delete from statistics.imported_observations_raw where true;

delete from statistics.observations where true;
delete from statistics.cases where true;

copy statistics.imported_observations_raw
    from 'C:\privat\misha\mody\dbimport\2022-05-15\targetTableOlga.csv'
    delimiter ','
    encoding 'utf8'
    csv header;

insert into statistics.cases (case_no,
                              last_name,
                              first_name,
                              otchestvo,
                              sex,
                              date_of_birth,
                              age_when_disorders_were_found_years,
                              age_when_disorders_were_found_months,
                              final_diagnosis)
select max(case_no),
       trim(max(last_name)),
       trim(max(first_name)),
       trim(max(otchestvo)),
       statistics.parse_sex(max(sex), 'м', 'ж'),
       to_date(max(date_of_birth), 'yyyy-mm-dd'),
       statistics.parse_int(min(age_when_disorders_were_found_years)),
       statistics.parse_int(min(age_when_disorders_were_found_months)),
       max(final_diagnosis)
from statistics.imported_observations_raw
group by case_no;


insert into statistics.observations (case_uuid,
                                     observation_no,
                                     age_when_examination_years,
                                     age_when_examination_months,
                                     ketosis_at_manifestation,
                                     polyuria,
                                     polydipsia,
                                     glucosuria,
                                     weight_loss,
                                     healthy,
                                     gestational_diabetes,
                                     glucose_intolerance,
                                     violation_of_glycemia_fasting,
                                     diabetes,
                                     birth_height,
                                     birth_weight,
                                     height_sds,
                                     weight_sds,
                                     body_mass_index_sds,
                                     cholesterol,
                                     triglycerides,
                                     duration_of_carbohydrate_metabolism_disorders,
                                     glycated_hemoglobin_for_diagnosis_HbA1C,
                                     glycated_hemoglobin_during_exm,
                                     degree_of_carbohydrate_metabolism_disorder,
                                     preliminary_diagnosis,
                                     diagnosis_on_examination,
                                     accompanying_illnesses,
                                     complications_of_diabetes,
                                     treatment_shortdesc,
                                     treatment_diet,
                                     treatment_insulin,
                                     treatment_liraglutide,
                                     treatment_metformin,
                                     treatment_sulfonylurea,
                                     glucose_fasting_min,
                                     glucose_fasting_max,
                                     postprandial_glucose_after_meals_max,
                                     OGTT_glucose_test_fasting,
                                     OGTT_glucose_test_30,
                                     OGTT_glucose_test_60,
                                     OGTT_glucose_test_90,
                                     OGTT_glucose_test_120,
                                     OGTT_insulin_test_fasting,
                                     OGTT_insulin_test_30,
                                     OGTT_insulin_test_60,
                                     OGTT_insulin_test_90,
                                     OGTT_insulin_test_120,
                                     OGTT_C_peptide_test_fasting,
                                     OGTT_C_peptide_test_30,
                                     OGTT_C_peptide_test_60,
                                     OGTT_C_peptide_test_90,
                                     OGTT_C_peptide_test_120,
                                     glucose_with_breakfast_test_fasting,
                                     glucose_with_breakfast_test_30,
                                     glucose_with_breakfast_test_60,
                                     glucose_with_breakfast_test_90,
                                     glucose_with_breakfast_test_120,
                                     insulin_with_breakfast_test_fasting,
                                     insulin_with_breakfast_test_30,
                                     insulin_with_breakfast_test_60,
                                     insulin_with_breakfast_test_90,
                                     insulin_with_breakfast_test_120,
                                     c_peptide_with_breakfast_test_fasting,
                                     c_peptide_with_breakfast_test_30,
                                     c_peptide_with_breakfast_test_60,
                                     c_peptide_with_breakfast_test_90,
                                     c_peptide_with_breakfast_test_120,
                                     IAA_to_insulin,
                                     ICA_to_pancreatic_beta_cells,
                                     GAD_glutamate_decarboxylase,
                                     IA2_to_tyrosine_phosphatase,
                                     ZnT8_to_zinc_transporter,
                                     HLA_gt_1_DRB1,
                                     HLA_gt_1_DQA1,
                                     HLA_gt_1_DQB1,
                                     HLA_gt_2_DRB1,
                                     HLA_gt_2_DQA1,
                                     HLA_gt_2_DQB1,
                                     notes_on_trees,
                                     gene,
                                     mutation)
select c.uuid,
       statistics.parse_int(observation_no),
       statistics.parse_int(age_when_observation_years),
       statistics.parse_int(age_when_observation_months),
       statistics.parse_bool(ketosis_at_manifestation, 'да'),
       statistics.parse_bool('Да', 'да'),
       statistics.parse_bool(polydipsia, 'да'),
       statistics.parse_bool(glucosuria, 'да'),
       statistics.parse_bool(weight_loss, 'да'),
       statistics.parse_bool(healthy, 'да'),
       statistics.parse_bool(gestational_diabetes, 'да'),
       statistics.parse_bool(glucose_intolerance, 'да'),
       statistics.parse_bool(violation_of_glycemia_fasting, 'да'),
       statistics.parse_bool(diabetes, 'да'),
       statistics.parse_int(birth_height),
       statistics.parse_int(birth_weight),
       statistics.parse_real(height_sds),
       statistics.parse_real(weight_sds),
       statistics.parse_real(body_mass_index_sds),
       statistics.parse_real(cholesterol),
       statistics.parse_real(triglycerides),
       statistics.parse_real(duration_of_carbohydrate_metabolism_disorders),
       statistics.parse_real(glycated_hemoglobin_for_diagnosis_HbA1C),
       statistics.parse_real(glycated_hemoglobin_during_exm),
       degree_of_carbohydrate_metabolism_disorder,
       preliminary_diagnosis,
       diagnosis_on_examination,
       accompanying_illnesses,
       complications_of_diabetes,
       treatment_shortdesc,
       treatment_diet,
       statistics.parse_real(treatment_insulin),
       statistics.parse_real(treatment_liraglutide),
       statistics.parse_real(treatment_metformin),
       statistics.parse_real(treatment_sulfonylurea),
       statistics.parse_real(glucose_fasting_min),
       statistics.parse_real(glucose_fasting_max),
       statistics.parse_real(postprandial_glucose_after_meals_max),
       statistics.parse_real(OGTT_glucose_test_fasting),
       statistics.parse_real(OGTT_glucose_test_30),
       statistics.parse_real(OGTT_glucose_test_60),
       statistics.parse_real(OGTT_glucose_test_90),
       statistics.parse_real(OGTT_glucose_test_120),
       statistics.parse_real(OGTT_insulin_test_fasting),
       statistics.parse_real(OGTT_insulin_test_30),
       statistics.parse_real(OGTT_insulin_test_60),
       statistics.parse_real(OGTT_insulin_test_90),
       statistics.parse_real(OGTT_insulin_test_120),
       statistics.parse_real(OGTT_C_peptide_test_fasting),
       statistics.parse_real(OGTT_C_peptide_test_30),
       statistics.parse_real(OGTT_C_peptide_test_60),
       statistics.parse_real(OGTT_C_peptide_test_90),
       statistics.parse_real(OGTT_C_peptide_test_120),
       statistics.parse_real(glucose_with_breakfast_test_fasting),
       statistics.parse_real(glucose_with_breakfast_test_30),
       statistics.parse_real(glucose_with_breakfast_test_60),
       statistics.parse_real(glucose_with_breakfast_test_90),
       statistics.parse_real(glucose_with_breakfast_test_120),
       statistics.parse_real(insulin_with_breakfast_test_fasting),
       statistics.parse_real(insulin_with_breakfast_test_30),
       statistics.parse_real(insulin_with_breakfast_test_60),
       statistics.parse_real(insulin_with_breakfast_test_90),
       statistics.parse_real(insulin_with_breakfast_test_120),
       statistics.parse_real(c_peptide_with_breakfast_test_fasting),
       statistics.parse_real(c_peptide_with_breakfast_test_30),
       statistics.parse_real(c_peptide_with_breakfast_test_60),
       statistics.parse_real(c_peptide_with_breakfast_test_90),
       statistics.parse_real(c_peptide_with_breakfast_test_120),
       statistics.parse_real(IAA_to_insulin),
       statistics.parse_real(ICA_to_pancreatic_beta_cells),
       statistics.parse_real(GAD_glutamate_decarboxylase),
       statistics.parse_real(IA2_to_tyrosine_phosphatase),
       statistics.parse_real(ZnT8_to_zinc_transporter),
       HLA_gt_1_DRB1,
       HLA_gt_1_DQA1,
       HLA_gt_1_DQB1,
       HLA_gt_2_DRB1,
       HLA_gt_2_DQA1,
       HLA_gt_2_DQB1,
       notes_on_trees,
       gene,
       mutation
from statistics.imported_observations_raw as r
         inner join
     statistics.cases as c
     on
         r.case_no = c.case_no;