copy statistics.source_observations_str
from 'C:\privat\misha\mody\report-2022-01-10\source\targetTableOlga.csv'
delimiter ','
encoding 'utf8'
CSV HEADER;

insert into
    statistics.cases (
            case_no,
            last_name,
            first_name,
            otchestvo,
            sex,
            date_of_birth,
            age_when_disorders_were_found_years,
            age_when_disorders_were_found_months,
            final_diagnosis)
    select
           max(case_no),
           max(last_name),
           max(first_name),
           max(otchestvo),
           case when max(sex)='ж' then 'f' else 'm' end,
           to_date(max(date_of_birth), 'yyyy-mm-dd'),
           to_number(min(age_when_disorders_were_found_years), '99999999D99')::int,
           case
               when to_number(min(age_when_disorders_were_found_months), '99999999D99')::int is not null
                    then to_number(min(age_when_disorders_were_found_months), '99999999D99')::int
                    else 0
           end,
           max(final_diagnosis)
    from statistics.source_observations_str
    group by case_no;


insert into
    statistics.observations (
           case_uuid,
           observation_no,
           age_when_examination_years,
           age_when_examination_months,
           ketosis_at_manifestation,
           polyuria,
           polydipsia,
           glucosuria,
           weight_loss,
           healthy,
           gestational_diabetes,
           glucose_intolerance,
           violation_of_glycemia_fasting,
           diabetes,
           birth_height,
           birth_weight,
           height_sds,
           weight_sds,
           body_mass_index_sds,
           cholesterol,
           triglycerides,
           duration_of_carbohydrate_metabolism_disorders,
           glycated_hemoglobin_for_diagnosis_HbA1C,
           glycated_hemoglobin_during_exm,
           degree_of_carbohydrate_metabolism_disorder,
           preliminary_diagnosis,
           diagnosis_on_examination,
           accompanying_illnesses,
           complications_of_diabetes,
           treatment_shortdesc,
           treatment_diet,
           treatment_insulin,
           treatment_liraglutide,
           treatment_metformin,
           treatment_sulfonylurea,
           glucose_fasting_min,
           glucose_fasting_max,
           postprandial_glucose_after_meals_max,
           OGTT_glucose_test_fasting,
           OGTT_glucose_test_30,
           OGTT_glucose_test_60,
           OGTT_glucose_test_90,
           OGTT_glucose_test_120,
           OGTT_insulin_test_fasting,
           OGTT_insulin_test_30,
           OGTT_insulin_test_60,
           OGTT_insulin_test_90,
           OGTT_insulin_test_120,
           OGTT_C_peptide_test_fasting,
           OGTT_C_peptide_test_30,
           OGTT_C_peptide_test_60,
           OGTT_C_peptide_test_90,
           OGTT_C_peptide_test_120,
           glucose_with_breakfast_test_fasting,
           glucose_with_breakfast_test_30,
           glucose_with_breakfast_test_60,
           glucose_with_breakfast_test_90,
           glucose_with_breakfast_test_120,
           insulin_with_breakfast_test_fasting,
           insulin_with_breakfast_test_30,
           insulin_with_breakfast_test_60,
           insulin_with_breakfast_test_90,
           insulin_with_breakfast_test_120,
           c_peptide_with_breakfast_test_fasting,
           c_peptide_with_breakfast_test_30,
           c_peptide_with_breakfast_test_60,
           c_peptide_with_breakfast_test_90,
           c_peptide_with_breakfast_test_120,
           IAA_to_insulin,
           ICA_to_pancreatic_beta_cells,
           GAD_glutamate_decarboxylase,
           IA2_to_tyrosine_phosphatase,
           ZnT8_to_zinc_transporter,
           HLA_gt_1_DRB1,
           HLA_gt_1_DQA1,
           HLA_gt_1_DQB1,
           HLA_gt_2_DRB1,
           HLA_gt_2_DQA1,
           HLA_gt_2_DQB1,
           notes_on_trees,
           gene,
           mutation
        )
    select
           c.uuid,
           to_number(examination_no, '99999'),
           to_number(age_when_examination_years, '99999'),
           to_number(age_when_examination_months, '99999'),
           case when ketosis_at_manifestation in ('Да', 'да') then true end,
           case when polyuria in ('Да', 'да') then true end,
           case when polydipsia in ('Да', 'да') then true end,
           case when glucosuria in ('Да', 'да') then true end,
           case when weight_loss in ('Да', 'да') then true end,
           case when healthy in ('Да', 'да') then true end,
           case when gestational_diabetes in ('Да', 'да') then true end,
           case when glucose_intolerance in ('Да', 'да') then true end,
           case when violation_of_glycemia_fasting in ('Да', 'да') then true end,
           case when diabetes in ('Да', 'да') then true end,
           case when birth_height ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(birth_height, '9999999D999999') end,
           case when birth_weight ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(birth_weight, '9999999D999999') end,
           case when height_sds ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(height_sds, '9999999D999999') end,
           case when weight_sds ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(weight_sds, '9999999D999999') end,
           case when body_mass_index_sds ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(body_mass_index_sds, '9999999D999999') end,
           case when cholesterol ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(cholesterol, '9999999D999999') end,
           case when triglycerides ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(triglycerides, '9999999D999999') end,
           case when duration_of_carbohydrate_metabolism_disorders ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(duration_of_carbohydrate_metabolism_disorders, '9999999D999999') end,
           case when glycated_hemoglobin_for_diagnosis_HbA1C ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(glycated_hemoglobin_for_diagnosis_HbA1C, '9999999D999999') end,
           case when glycated_hemoglobin_during_exm ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(glycated_hemoglobin_during_exm, '9999999D999999') end,
           degree_of_carbohydrate_metabolism_disorder,
           preliminary_diagnosis,
           diagnosis_on_examination,
           accompanying_illnesses,
           complications_of_diabetes,
           treatment_shortdesc,
           treatment_diet,
           case when treatment_insulin ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(treatment_insulin, '9999999D999999') end,
           case when treatment_liraglutide ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(treatment_liraglutide, '9999999D999999') end,
           case when treatment_metformin ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(treatment_metformin, '9999999D999999') end,
           case when treatment_sulfonylurea ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(treatment_sulfonylurea, '9999999D999999') end,
           case when glucose_fasting_min ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(glucose_fasting_min, '9999999D999999') end,
           case when glucose_fasting_max ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(glucose_fasting_max, '9999999D999999') end,
           case when postprandial_glucose_after_meals_max ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(postprandial_glucose_after_meals_max, '9999999D999999') end,
           case when OGTT_glucose_test_fasting ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(OGTT_glucose_test_fasting, '9999999D999999') end,
           case when OGTT_glucose_test_30 ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(OGTT_glucose_test_30, '9999999D999999') end,
           case when OGTT_glucose_test_60 ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(OGTT_glucose_test_60, '9999999D999999') end,
           case when OGTT_glucose_test_90 ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(OGTT_glucose_test_90, '9999999D999999') end,
           case when OGTT_glucose_test_120 ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(OGTT_glucose_test_120, '9999999D999999') end,
           case when OGTT_insulin_test_fasting ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(OGTT_insulin_test_fasting, '9999999D999999') end,
           case when OGTT_insulin_test_30 ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(OGTT_insulin_test_30, '9999999D999999') end,
           case when OGTT_insulin_test_60 ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(OGTT_insulin_test_60, '9999999D999999') end,
           case when OGTT_insulin_test_90 ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(OGTT_insulin_test_90, '9999999D999999') end,
           case when OGTT_insulin_test_120 ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(OGTT_insulin_test_120, '9999999D999999') end,
           case when OGTT_C_peptide_test_fasting ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(OGTT_C_peptide_test_fasting, '9999999D999999') end,
           case when OGTT_C_peptide_test_30 ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(OGTT_C_peptide_test_30, '9999999D999999') end,
           case when OGTT_C_peptide_test_60 ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(OGTT_C_peptide_test_60, '9999999D999999') end,
           case when OGTT_C_peptide_test_90 ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(OGTT_C_peptide_test_90, '9999999D999999') end,
           case when OGTT_C_peptide_test_120 ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(OGTT_C_peptide_test_120, '9999999D999999') end,
           case when glucose_with_breakfast_test_fasting ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(glucose_with_breakfast_test_fasting, '9999999D999999') end,
           case when glucose_with_breakfast_test_30 ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(glucose_with_breakfast_test_30, '9999999D999999') end,
           case when glucose_with_breakfast_test_60 ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(glucose_with_breakfast_test_60, '9999999D999999') end,
           case when glucose_with_breakfast_test_90 ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(glucose_with_breakfast_test_90, '9999999D999999') end,
           case when glucose_with_breakfast_test_120 ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(glucose_with_breakfast_test_120, '9999999D999999') end,
           case when insulin_with_breakfast_test_fasting ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(insulin_with_breakfast_test_fasting, '9999999D999999') end,
           case when insulin_with_breakfast_test_30 ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(insulin_with_breakfast_test_30, '9999999D999999') end,
           case when insulin_with_breakfast_test_60 ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(insulin_with_breakfast_test_60, '9999999D999999') end,
           case when insulin_with_breakfast_test_90 ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(insulin_with_breakfast_test_90, '9999999D999999') end,
           case when insulin_with_breakfast_test_120 ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(insulin_with_breakfast_test_120, '9999999D999999') end,
           case when c_peptide_with_breakfast_test_fasting ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(c_peptide_with_breakfast_test_fasting, '9999999D999999') end,
           case when c_peptide_with_breakfast_test_30 ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(c_peptide_with_breakfast_test_30, '9999999D999999') end,
           case when c_peptide_with_breakfast_test_60 ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(c_peptide_with_breakfast_test_60, '9999999D999999') end,
           case when c_peptide_with_breakfast_test_90 ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(c_peptide_with_breakfast_test_90, '9999999D999999') end,
           case when c_peptide_with_breakfast_test_120 ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(c_peptide_with_breakfast_test_120, '9999999D999999') end,
           case when IAA_to_insulin ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(IAA_to_insulin, '9999999D999999') end,
           case when ICA_to_pancreatic_beta_cells ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(ICA_to_pancreatic_beta_cells, '9999999D999999') end,
           case when GAD_glutamate_decarboxylase ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(GAD_glutamate_decarboxylase, '9999999D999999') end,
           case when IA2_to_tyrosine_phosphatase ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(IA2_to_tyrosine_phosphatase, '9999999D999999') end,
           case when ZnT8_to_zinc_transporter ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(ZnT8_to_zinc_transporter, '9999999D999999') end,
           case when HLA_gt_1_DRB1 ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(HLA_gt_1_DRB1, '9999999D999999') end,
           case when HLA_gt_1_DQA1 ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(HLA_gt_1_DQA1, '9999999D999999') end,
           case when HLA_gt_1_DQB1 ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(HLA_gt_1_DQB1, '9999999D999999') end,
           case when HLA_gt_2_DRB1 ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(HLA_gt_2_DRB1, '9999999D999999') end,
           case when HLA_gt_2_DQA1 ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(HLA_gt_2_DQA1, '9999999D999999') end,
           case when HLA_gt_2_DQB1 ~ '(\s*)(\d+)((,\d*)?)(\s*)' then to_number(HLA_gt_2_DQB1, '9999999D999999') end,
           notes_on_trees,
           gene,
           mutation
    from
         statistics.source_observations_str as s
             inner join
         statistics.cases as c
             on
         s.case_no = c.case_no;

